### PR TITLE
csp-solver gem

### PR DESCRIPTION
**Pull request by mooreniemi**
Check out [this source](http://guides.rubygems.org/name-your-gem/) for details on why I changed the namespacing the way that I did. It shouldn't change any behavior: just following convention. Also don't be alarmed at the syntax changes: I made use of [rubocop](https://github.com/bbatsov/rubocop), again to follow convention.

I still have a few things left to do (I'd like to specifically put specs in showing the `mathdoku` and `sudoku` `Problem`s) but I wanted to make this PR now so you could get a chance to start looking at it.

### CODE REVIEW

**Comment by komputerwiz** [comment]
Wow, that was fast! I've merged your pull request into my `develop` branch and started a `release/0.1.0` branch from it. I'll look over the changes and then merge the release branch.

**Comment by komputerwiz** [comment]
refs #3

**Comment by mooreniemi** [comment]
still want to publish this as a gem? i can do it for you too if you like. i'd ask for a secondary author credit if it's ok

**Comment by komputerwiz** [comment]
Thanks for bringing this back to my attention! I put this on hold for a while and totally forgot about it. My apologies.

I'll have a chance to look into publishing it this weekend (*_sets reminder on calendar_*). And don't worry, you'll definitely get author credit since you were the one who organized it into a gem in the first place.

**Pull request closed without merging**
